---
include:
  - board: nice_nano//zmk
    shield: lily58_left nice_view_adapter nice_view
  - board: nice_nano//zmk
    shield: lily58_right nice_view_adapter nice_view
  - board: nice_nano//zmk
    shield: settings_reset
